modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory
license="All rights reserved"

[[mods]] #mandatory
modId="nebs" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Neko's Enchanted Books" #mandatory
updateJSONURL="https://infernalstudios.org/api/mods/nekosenchantedbooks/forge"
credits="Nekomaster, CGessinger" #optional
authors="Infernal Studios"
description='''A small mod that adds unique textures to every Enchanted Book in vanilla Minecraft, in addition to every book in the mods...
- Ensorcellation
- Veinmining
- Charm
- Wall-Jump!
- Apotheosis
- Jellyfishing
- VanillaTweaks
- BetterDefaultBiomes
- Wonderful Enchantments
- Shulker Enchantments
- Step, Leap, Dash
- Farmer's Delight
- Alex's Mobs
- Allurement
- Momentum
- Elenai Dodge 2
- Advent of Ascension 3
- Greed N' Bleed
- Create
- Corpse Complex
- BetterEnd (Forge)
- Locks
- Big Brain
- Mining Master
- Seeker's Compass
- Ma Enchants
- Brooms
- Fins and Tails
- Supplementaries
'''

[[dependencies.nebs]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="CLIENT"

[[dependencies.nebs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.nebs]]
    modId="wonderful_enchantments"
    mandatory=false
    versionRange="[1.0.0,)"
    ordering="BEFORE"
    side="CLIENT"

[[dependencies.nebs]]
    modId="inspirations"
    mandatory=false
    versionRange="[1.0.0,)"
    ordering="BEFORE"
    side="CLIENT"

[[dependencies.nebs]]
    modId="maenchants"
    mandatory=false
    versionRange="[1.0.0,)"
    ordering="BEFORE"
    side="CLIENT"

