modLoader="javafml"
loaderVersion="[50,)"
license="All rights reserved"
clientSideOnly=true

[[mods]]
modId="nebs"
version="${file.jarVersion}"
displayName="Neko's Enchanted Books"
updateJSONURL="https://infernalstudios.org/api/mods/nekosenchantedbooks/forge"
credits="Nekomaster, CGessinger, Jonathing"
authors="Infernal Studios"
description='''A small mod that enables adding unique textures for Enchanted Books. See our mod's page for more details on what mods are natively supported and how you can add your own support!'''

[[dependencies.nebs]]
    modId="forge"
    mandatory=true
    versionRange="[50,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.nebs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.6,1.21)"
    ordering="NONE"
    side="CLIENT"
